name: Deploy IPA/DEB/DYLIB Archive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow

    - name: Create necessary directories
      run: |
        mkdir -p ipa
        mkdir -p deb
        mkdir -p dylib
        mkdir -p _data
        mkdir -p assets/app-icons

    - name: Process IPA files (with debug)
      run: |
        echo "↪ CWD is $(pwd)"
        python .github/scripts/process_ipa.py
        echo "↪ After process_ipa.py, _data contains:"
        ls -R _data || echo "  (empty or missing)"

    - name: Generate file index (with debug)
      run: |
        echo "↪ CWD is $(pwd)"
        python .github/scripts/generate_index.py
        echo "↪ After generate_index.py, _data contains:"
        ls -R _data || echo "  (empty or missing)"

    - name: Upload _data directory as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-directory
        path: _data/

    - name: Upload assets directory as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: assets-directory
        path: assets/
