name: Deploy IPA/DEB/DYLIB Archive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Create necessary directories
      run: |
        mkdir -p ipa
        mkdir -p deb
        mkdir -p dylib
        mkdir -p _data
        
    - name: Generate file index
      run: |
        python .github/scripts/generate_index.py
        
    - name: Upload file index as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: file-index
        path: _data/files_index.json
