name: Deploy IPA/DEB/DYLIB Archive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow plistlib
        
    - name: Create necessary directories
      run: |
        mkdir -p ipa
        mkdir -p deb
        mkdir -p dylib
        mkdir -p _data
        mkdir -p assets/app-icons
        
    - name: Process IPA files
      run: |
        python .github/scripts/process_ipa.py
        
    - name: Generate file index
      run: |
        python .github/scripts/generate_index.py
        
    - name: Upload file index as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: file-index
        path: _data/files_index.json
        
    - name: Upload IPA data as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipa-data
        path: _data/ipa_data.json
